In [3]:
import json
import pandas as pd

In [7]:
file_path = 'data/initial_data.json'

with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

print(data)

{'accounts': [{'account_id': 'acc-001', 'owner_id': 'user-001', 'nickname': '생활비', 'balance': 1431800}, {'account_id': 'acc-002', 'owner_id': 'user-001', 'nickname': '저축', 'balance': 2280000}, {'account_id': 'acc-003', 'owner_id': 'user-001', 'nickname': '여행 자금', 'balance': 390000}, {'account_id': 'acc-004', 'owner_id': 'user-002', 'nickname': '생활비', 'balance': 850000}, {'account_id': 'acc-005', 'owner_id': 'user-003', 'nickname': '저축', 'balance': 1200000}], 'cards': [{'card_id': 'card-001', 'owner_id': 'user-001', 'name': '생활비 카드', 'account_id': 'acc-001', 'status': 'active', 'card_number': '0000-0000-0000-0001', 'card_type': 'debit'}, {'card_id': 'card-002', 'owner_id': 'user-001', 'name': '여행 카드', 'account_id': 'acc-003', 'status': 'active', 'card_number': '0000-0000-0000-0002', 'card_type': 'debit'}, {'card_id': 'card-003', 'owner_id': 'user-002', 'name': '생활비 카드', 'account_id': 'acc-004', 'status': 'active', 'card_number': '0000-0000-0000-0003', 'card_type': 'debit'}, {'card_id': 'card-004', 'owner_id': 'user-003', 'name': '생활비 카드', 'account_id': 'acc-005', 'status': 'active', 'card_number': '0000-0000-0000-0004', 'card_type': 'debit'}], 'transactions': [{'transaction_id': 'tx-001', 'owner_id': 'user-001', 'account_id': 'acc-001', 'type': 'deposit', 'amount': 300000, 'occurred_at': '2026-08-28T10:00:00+09:00', 'card_id': None, 'merchant': None}, {'transaction_id': 'tx-002', 'owner_id': 'user-001', 'account_id': 'acc-001', 'type': 'withdrawal', 'amount': 52000, 'occurred_at': '2026-08-30T11:00:00+09:00', 'card_id': 'card-001', 'merchant': '마트'}, {'transaction_id': 'tx-003', 'owner_id': 'user-001', 'account_id': 'acc-001', 'type': 'deposit', 'amount': 1000000, 'occurred_at': '2026-09-01T12:00:00+09:00', 'card_id': None, 'merchant': None}, {'transaction_id': 'tx-004', 'owner_id': 'user-001', 'account_id': 'acc-002', 'type': 'deposit', 'amount': 200000, 'occurred_at': '2026-09-02T13:00:00+09:00', 'card_id': None, 'merchant': None}, {'transaction_id': 'tx-005', 'owner_id': 'user-001', 'account_id': 'acc-003', 'type': 'deposit', 'amount': 150000, 'occurred_at': '2026-09-03T14:00:00+09:00', 'card_id': None, 'merchant': None}, {'transaction_id': 'tx-006', 'owner_id': 'user-001', 'account_id': 'acc-001', 'type': 'withdrawal', 'amount': 6500, 'occurred_at': '2026-09-04T15:00:00+09:00', 'card_id': 'card-001', 'merchant': '편의점'}, {'transaction_id': 'tx-007', 'owner_id': 'user-001', 'account_id': 'acc-001', 'type': 'withdrawal', 'amount': 72000, 'occurred_at': '2026-09-05T16:00:00+09:00', 'card_id': 'card-001', 'merchant': '마트'}, {'transaction_id': 'tx-008', 'owner_id': 'user-001', 'account_id': 'acc-003', 'type': 'withdrawal', 'amount': 55000, 'occurred_at': '2026-09-06T17:00:00+09:00', 'card_id': 'card-002', 'merchant': '철도'}, {'transaction_id': 'tx-009', 'owner_id': 'user-001', 'account_id': 'acc-001', 'type': 'withdrawal', 'amount': 15000, 'occurred_at': '2026-09-07T18:00:00+09:00', 'card_id': 'card-001', 'merchant': '식당'}, {'transaction_id': 'tx-010', 'owner_id': 'user-001', 'account_id': 'acc-002', 'type': 'deposit', 'amount': 50000, 'occurred_at': '2026-09-08T09:00:00+09:00', 'card_id': None, 'merchant': None}, {'transaction_id': 'tx-011', 'owner_id': 'user-001', 'account_id': 'acc-001', 'type': 'withdrawal', 'amount': 100000, 'occurred_at': '2026-09-09T10:00:00+09:00', 'card_id': None, 'merchant': None}, {'transaction_id': 'tx-012', 'owner_id': 'user-001', 'account_id': 'acc-003', 'type': 'withdrawal', 'amount': 80000, 'occurred_at': '2026-09-10T11:00:00+09:00', 'card_id': 'card-002', 'merchant': '호텔'}, {'transaction_id': 'tx-013', 'owner_id': 'user-001', 'account_id': 'acc-001', 'type': 'withdrawal', 'amount': 50000, 'occurred_at': '2026-09-11T12:00:00+09:00', 'card_id': 'card-001', 'merchant': '서점'}, {'transaction_id': 'tx-014', 'owner_id': 'user-001', 'account_id': 'acc-001', 'type': 'withdrawal', 'amount': 12000, 'occurred_at': '2026-09-12T13:00:00+09:00', 'card_id': 'card-001', 'merchant': '식당'}, {'transaction_id': 'tx-015', 'owner_id': 'user-001', 'account_id': 'acc-003', 'type': 'deposit', 'amount': 100000, 'occurred_at': '2026-09-14T14:00:00+09:00', 'card_id': None, 'merchant': None}, {'transaction_id': 'tx-016', 'owner_id': 'user-001', 'account_id': 'acc-001', 'type': 'withdrawal', 'amount': 48000, 'occurred_at': '2026-09-16T15:00:00+09:00', 'card_id': 'card-001', 'merchant': '마트'}, {'transaction_id': 'tx-017', 'owner_id': 'user-001', 'account_id': 'acc-003', 'type': 'withdrawal', 'amount': 25000, 'occurred_at': '2026-09-18T16:00:00+09:00', 'card_id': 'card-002', 'merchant': '식당'}, {'transaction_id': 'tx-018', 'owner_id': 'user-001', 'account_id': 'acc-002', 'type': 'deposit', 'amount': 30000, 'occurred_at': '2026-09-19T17:00:00+09:00', 'card_id': None, 'merchant': None}, {'transaction_id': 'tx-019', 'owner_id': 'user-001', 'account_id': 'acc-001', 'type': 'withdrawal', 'amount': 4500, 'occurred_at': '2026-09-20T18:00:00+09:00', 'card_id': 'card-001', 'merchant': '편의점'}, {'transaction_id': 'tx-020', 'owner_id': 'user-001', 'account_id': 'acc-001', 'type': 'withdrawal', 'amount': 8200, 'occurred_at': '2026-09-20T09:00:00+09:00', 'card_id': 'card-001', 'merchant': '편의점'}], 'addresses': [{'address_id': 'addr-home', 'owner_id': 'user-001', 'label': '집', 'address': '가상시 가상구 집로 10'}, {'address_id': 'addr-work', 'owner_id': 'user-001', 'label': '회사', 'address': '가상시 가상구 회사로 20'}], 'requests': [], 'reissue_applications': [], 'bills': [{'bill_id': 'bill-001', 'owner_id': 'user-001', 'name': '통신비', 'amount': 55000, 'due_date': '2026-09-22', 'status': 'unpaid'}, {'bill_id': 'bill-002', 'owner_id': 'user-001', 'name': '전기요금', 'amount': 42000, 'due_date': '2026-09-25', 'status': 'unpaid'}, {'bill_id': 'bill-003', 'owner_id': 'user-001', 'name': '수도요금', 'amount': 18000, 'due_date': '2026-09-27', 'status': 'unpaid'}, {'bill_id': 'bill-004', 'owner_id': 'user-001', 'name': '관리비', 'amount': 130000, 'due_date': '2026-09-30', 'status': 'unpaid'}, {'bill_id': 'bill-005', 'owner_id': 'user-001', 'name': '가스요금', 'amount': 25000, 'due_date': '2026-09-18', 'status': 'unpaid'}]}

In [8]:
data.keys()

dict_keys(['accounts', 'cards', 'transactions', 'addresses', 'requests', 'reissue_applications', 'bills'])

In [9]:
accounts = pd.DataFrame.from_dict(data['accounts'])
accounts

  account_id  owner_id nickname  balance
0    acc-001  user-001      생활비  1431800
1    acc-002  user-001       저축  2280000
2    acc-003  user-001    여행 자금   390000
3    acc-004  user-002      생활비   850000
4    acc-005  user-003       저축  1200000

In [11]:
cards = pd.DataFrame.from_dict(data['cards'])
cards

,card_id,owner_id,name,account_id,status,card_number,card_type
0,card-001,user-001,생활비 카드,acc-001,active,0000-0000-0000-0001,debit
1,card-002,user-001,여행 카드,acc-003,active,0000-0000-0000-0002,debit
2,card-003,user-002,생활비 카드,acc-004,active,0000-0000-0000-0003,debit
3,card-004,user-003,생활비 카드,acc-005,active,0000-0000-0000-0004,debit

In [15]:
transactions = pd.DataFrame.from_dict(data['transactions'])
transactions

,transaction_id,owner_id,account_id,type,amount,occurred_at,card_id,merchant
0,tx-001,user-001,acc-001,deposit,300000,2026-08-28T10:00:00+09:00,NaN,NaN
1,tx-002,user-001,acc-001,withdrawal,52000,2026-08-30T11:00:00+09:00,card-001,마트
2,tx-003,user-001,acc-001,deposit,1000000,2026-09-01T12:00:00+09:00,NaN,NaN
3,tx-004,user-001,acc-002,deposit,200000,2026-09-02T13:00:00+09:00,NaN,NaN
4,tx-005,user-001,acc-003,deposit,150000,2026-09-03T14:00:00+09:00,NaN,NaN
5,tx-006,user-001,acc-001,withdrawal,6500,2026-09-04T15:00:00+09:00,card-001,편의점
6,tx-007,user-001,acc-001,withdrawal,72000,2026-09-05T16:00:00+09:00,card-001,마트
7,tx-008,user-001,acc-003,withdrawal,55000,2026-09-06T17:00:00+09:00,card-002,철도
8,tx-009,user-001,acc-001,withdrawal,15000,2026-09-07T18:00:00+09:00,card-001,식당
9,tx-010,user-001,acc-002,deposit,50000,2026-09-08T09:00:00+09:00,NaN,NaN
10,tx-011,user-001,acc-001,withdrawal,100000,2026-09-09T10:00:00+09:00,NaN,NaN
11,tx-012,user-001,acc-003,withdrawal,80000,2026-09-10T11:00:00+09:00,card-002,호텔
12,tx-013,user-001,acc-001,withdrawal,50000,2026-09-11T12:00:00+09:00,card-001,서점
13,tx-014,user-001,acc-001,withdrawal,12000,2026-09-12T13:00:00+09:00,card-001,식당
14,tx-015,user-001,acc-003,deposit,100000,2026-09-14T14:00:00+09:00,NaN,NaN
15,tx-016,user-001,acc-001,withdrawal,48000,2026-09-16T15:00:00+09:00,card-001,마트
16,tx-017,user-001,acc-003,withdrawal,25000,2026-09-18T16:00:00+09:00,card-002,식당
17,tx-018,user-001,acc-002,deposit,30000,2026-09-19T17:00:00+09:00,NaN,NaN
18,tx-019,user-001,acc-001,withdrawal,4500,2026-09-20T18:00:00+09:00,card-001,편의점
19,tx-020,user-001,acc-001,withdrawal,8200,2026-09-20T09:00:00+09:00,card-001,편의점

In [17]:
addresses = pd.DataFrame.from_dict(data['addresses'])
addresses

  address_id  owner_id label         address
0  addr-home  user-001     집   가상시 가상구 집로 10
1  addr-work  user-001    회사  가상시 가상구 회사로 20

In [19]:
requests = pd.DataFrame.from_dict(data['requests'])
requests

Empty DataFrame
Columns: []
Index: []

In [20]:
reissue_apps = pd.DataFrame.from_dict(data['reissue_applications'])
reissue_apps

Empty DataFrame
Columns: []
Index: []

In [21]:
bills = pd.DataFrame.from_dict(data['bills'])
bills

    bill_id  owner_id  name  amount    due_date  status
0  bill-001  user-001   통신비   55000  2026-09-22  unpaid
1  bill-002  user-001  전기요금   42000  2026-09-25  unpaid
2  bill-003  user-001  수도요금   18000  2026-09-27  unpaid
3  bill-004  user-001   관리비  130000  2026-09-30  unpaid
4  bill-005  user-001  가스요금   25000  2026-09-18  unpaid

In [22]:
bills.to_csv('data/dataframes/bills.csv', index=False, encoding='utf-8-sig')

In [18]:
addresses.to_csv('data/dataframes/addresses.csv', index=False, encoding='utf-8-sig')

In [12]:
accounts.to_csv('data/dataframes/accounts.csv', index=False, encoding='utf-8-sig')

In [14]:
cards.to_csv('data/dataframes/cards.csv', index=False, encoding='utf-8-sig')

In [16]:
transactions.to_csv('data/dataframes/transactions.csv', index=False, encoding='utf-8-sig')

- bank_account_balance 노드의 state의 fields는 request(사용자 요청: 부모 state의 messages 필드와 연동), owner_id, account_id, nickname, balance를 필요로 하는데 이걸 
- 부모 field를 Accounts(BaseModel)로 만들어서 이 안에 이런 것들을 다 집어넣어서 사용하면 어떨까?
-

### 은행 계좌 잔액 조회 업무 흐름
1. 사용자가 은행 계좌 잔액을 조회하는 요청이 온다.
2. 사용자 요청이 어떤 서비스를 요구하는지를 분석해서 그 작업에 맞는 subagent에게 작업을 분배하는 역할을 하는 supervisor 노드가 이 작업을 bank_account_balance라는 subagent에게 보낸다.
3. 만약 사용자 요청안에 잔액 조회를 원하는 account_id가 있는지 확인해서 있다면 tool인 get_balance_by_owner(ower_id, account_id)를 갖고 있는 graph(=create_agent(model, llm, checkpointer)를 
    invoke해서 구하고 만약 account_id가 없다면 graph가 해당 owner_id는 몇개의 account를 갖고 있는지 확인해서 그 정보를 Human-in-the-loop의 Command, interrupt를 이용해서 사용자로부터 선택을 받아서
    거기에 맞게 정보를 제공한다.)

In [7]:
from pydantic import BaseModel, Field
from typing import TypedDict, Annotated
from langgraph.graph.message import add_messages
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.tools import tool
from langchain.agents import create_agent
import os
from dotenv import load_dotenv

load_dotenv()

GEMINI_MODEL = os.getenv('GEMINI_MODEL')
llm = ChatGoogleGenerativeAI(model=GEMINI_MODEL)

In [2]:
class Account(BaseModel):
    account_id: str = Field(description="계좌 번호")
    owner_id: str = Field(description="계좌 소유주의 아이디")
    nickname: str = Field(description="계좌의 주된 용도")
    balance: int = Field(description="계좌 잔액")

class AccountState(TypedDict):
    messages: Annotated[list, add_messages]
    owner_account: list[Account]

In [ ]:
@tool(parse_docstring=True)
def get_balance_by_owner(owner_id: str, account_id: str | None = None) -> str:
    """계좌 잔액을 조회한다.
    
    Args:
        owner_id: 계좌 소유주의 아이디
        account_id: 조회할 계좌 번호. 생략하면 (None) 해당 owner_id의 모든 계좌를 조회한다.
    """
    file_path = 'data/data.json'

    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    matched = [
        account for account in data['accounts']
        if account['owner_id'] == owner_id and (account_id is None or account['account_id'] == account_id)
    ]

    if not matched:
        return json.dumps({'found': False, 'accounts': []})

    return json.dumps({
        'found': True,
        'accounts': [
            {'account_id': acc['account_id'], 'balance': acc['balance']} for acc in matched
        ]
    })

In [ ]:
def account_agent(state: AccountState):
    # 사용자 요청을 받는다
    request = state['messages'][-1]
    graph = create_agent(model=llm, tools=[get_balance_by_owner])

1. request(사용자 요청을 받는다)

In [8]:
my_list = [1, 2, 3, 4, 5]
my_iter = iter(my_list)
print(my_iter)

for i in range(len(my_list) + 3):
    print(f'{i+1}번째: {next(my_iter, "rubin")}')

<list_iterator object at 0x0000019291D98E50>
1번째: 1
2번째: 2
3번째: 3
4번째: 4
5번째: 5
6번째: rubin
7번째: rubin
8번째: rubin